### ISSUE TITLE
Default scope for the request asks for write permissions

### ISSUE THREAD

**Issue by LenPayne** [ueberauth/ueberauth_github#31]
The default scope of the OAuth request uses `user,public_repo`, which [give full read/write access to a user's public profile](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/).

This can be a security flaw. If a service were compromised, it could be used to re-write GitHub user emails or delete repositories.

Perhaps the default should change to `user:email`, or no scope at all.

Or perhaps a little addition to the README would be useful to identify how to get read-only access (ie- use `default_scope: 'user:email'` or `default_scope: ''` as above.)

**Comment by doomspork** [comment]
@LenPayne this sounds like a reasonable solution, would you like to open a PR?  I think it would be safer to start with a README change and see how that goes.

**Comment by silently** [comment]
Additionnally and if the app requires no scope at all, an error is currently raised during callback: "Unable to access the user's email address".

This is because the `%Info` struct email field is initialized with the function `fetch_email!` that raises an error rather than returning nil in case no email is known. I think using a non raising version of `fetch_email` would be valid.

Usecase: using github only to get the unique user identifier of the oauth provider.

**Comment by doomspork** [comment]
@silently follow-up PRs to improve what we have are always welcomed 👍
