### ISSUE TITLE
Github strategy not working in Phoenix 1.7.0

### ISSUE THREAD

**Issue by EduardoBorsa** [ueberauth/ueberauth_github#75]
### Steps to Reproduce

create an application in phoenix 1.7.
Setup GitHub strategy.
Try to log in.

### Expected Result

should authenticate you

### Actual Result

Returns error.

Works fine in phoenix 1.6

**Comment by sltong** [comment]
I'm assuming you're getting the error below, correct?
```
[warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
    Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
```

Check your dependencies for `oauth2` (e.g. in your `mix.lock`). If it's version `2.1.0`, then the error is probably due to `Hackney` no longer being the HTTP client for `oauth2`, but [Tesla](https://hexdocs.pm/tesla/readme.html). Tesla uses the `httpc` adapter which doesn't configure certs by default, AFAIK.

Since Phoenix 1.7 uses [Finch](https://hexdocs.pm/finch/Finch.html) for its HTTP adapter, it's a matter of configuring `oauth2` for Finch.

What I did to resolve the issue was putting this in my `config.ex`:
```
config :oauth2, :adapter, {Tesla.Adapter.Finch, name: MyApp.Finch}
```

**Comment by yordis** [comment]
@EduardoBorsa feel free to reopen the issue if @sltong solution didn't help
